### ISSUE TITLE
Reduce h3 font size on mobile to 24px

### ISSUE THREAD

**Issue by Mtankha** [metmuseum/marble#118]
The scaling algorithm for h3 should be adjusted so that on a mobile (375px width) screen the pixel size is 24px. This will ensure better type hierarchy with the other headings/body text on mobile. See attached for sizing guidelines for all headings.

<img width="1128" alt="Screen Shot 2021-04-21 at 12 22 06 PM" src="https://user-images.githubusercontent.com/8670407/115588095-62232380-a29c-11eb-86e6-1c97078b0f23.png">

**Comment by stephenhmarsh** [comment]
Fixed by #125

**Comment by stephenhmarsh** [comment]
Fixed by #125
